# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/71e77fb3-be64-4f09-addd-6820b12f22d1";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/9A3D-C22F";
      fsType = "vfat";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/cc35d034-94d3-4886-a02b-2bb54957ef86";
      fsType = "ext4";
    };

#  fileSystems."/eth" =
 #   { device = "/dev/disk/by-uuid/182179ea-a124-4c44-a41a-048acb58afdf";
  #    fsType = "ext4";
   # };

  fileSystems."/gig1" =
    { device = "/dev/disk/by-uuid/726f7738-97a0-4ab7-97b7-16a80aa1a4b2";                                                                                               
      fsType = "ext4";                                                                                                                                                 
    };                    

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ef76d96a-acde-4ca6-a931-aba7de10dead"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
